#ifndef COM_MASTECH_MS8050_LIB_GLOBAL_H
#define COM_MASTECH_MS8050_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LAMPHLIB_LIBRARY)
#  define LAMPHLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LAMPHLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COM_MASTECH_MS8050_LIB_GLOBAL_H
